version: '3.8'

services:
  # 1. Service Database
  mysql_db:
    image: mysql:8.0
    container_name: my_mysql_container
    restart: always
    environment:
      # Map biến từ file .env vào biến môi trường của MySQL
      MYSQL_DATABASE: test_database
      MYSQL_ROOT_PASSWORD: N0th1ngSp3cial
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql # Mount volume để không mất dữ liệu khi tắt container
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # 2. Service Backend (Spring Boot App)
  backend-app:
    # Thay thế bằng tên image thực tế của bạn trên Docker Hub
    image: ${DOCKER_USERNAME}/spring-base-project:latest
    container_name: my_spring_app
    restart: on-failure
    depends_on:
      mysql_db:
        condition: service_healthy # Chỉ chạy App sau khi DB đã khởi động xong
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}" # 8080:8080
    env_file:
      - .env
    networks:
      - backend-network

# Định nghĩa Volume để lưu dữ liệu DB bền vững
volumes:
  mysql_data:

# Định nghĩa Network để 2 container nhìn thấy nhau
networks:
  backend-network:
    driver: bridge