name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # 1. Lấy mã nguồn về
    - uses: actions/checkout@v4

    # 2. Đăng nhập vào Docker Hub (Sử dụng Secrets đã cài đặt)
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3. Cài đặt Docker Buildx (Công cụ build nâng cao giúp cache nhanh hơn)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # 4. Build và Push image
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        push: true # Lệnh này xác nhận sẽ Push lên Hub
        # Dưới đây là phần quan trọng: Gắn 2 tags cùng lúc
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/spring-base-project:${{ github.sha }}
          ${{ secrets.DOCKER_USERNAME }}/spring-base-project:latest
